---
# All rights reserved InspectorGadget
no-perm-message: "You do not have permisson to use this command, attempt was logged!"
# Banned Commands
banned-commands:
    - /setuperm
    - /op
    - /setgperm
    - /deop
# Allowed Players to use these commands - ALL IN LOWER CAPS
allowed-players:
    - ArandomUser101183
...
